baseURL: "https://kurtbruns.github.io/vector/"
languageCode: "en-us"
title: "Interactive SVG"
disableKinds: ["taxonomy", "taxonomyTerm"]
pygmentsUseClasses: true
canonifyURLs:  true
publishDir: "../docs/"
staticDir:
  - static
  - ../dist/

TODO: add source folder to also host typescript files?


params:
  repositoryURL: "https://github.com/KurtBruns/vector"
