baseURL: "https://vectorjs.org"
languageCode: "en-us"
title: "Vector.js"
disableKinds: ["taxonomy", "taxonomyTerm"]
pygmentsUseClasses: true
publishDir: "../docs/"
staticDir:
  - static
  - ../dist/

permalinks:
  tutorials: /:title/

params:
  repositoryURL: "https://github.com/vector-js/vector.git"
