image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

# install dependencies
dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

# run tests
test:
  stage: test
  script: npm test
